FROM node:20-slim

WORKDIR /app

COPY simulacion_scroll/package*.json ./

RUN npm install

COPY simulacion_scroll/ .
COPY videos/ /videos/

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
